### ISSUE TITLE
API Routing

### ISSUE THREAD

**Issue by rmainseas** [seas-computing/course-planner#109]
Look into API routing to add global `/api` prefix to all API controllers

**Comment by jonseitz** [comment]
This was implemented in #249, albeit in a slightly different fashion. We opted not to use `/api` as the global prefix, since there are some routes that shouldn't fall under the `/api/` namespace (e.g. `/login` and `/logout`). We did need to add a `/course-planner` prefix though, as part of our load balancer configuration.
