### ISSUE TITLE
Add cell highlighting for sabbatical / leaves in faculty table

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#300]
If a sabbatical type is selected, the cell for that semester is highlighted appropriately, as well as the "courses" cell to its immediate right. 

* @Vittorio2015 to mock up [color treatment for sabbatical options](https://github.com/seas-computing/course-planner/issues/300#issuecomment-771123009) (2.5 hours)
  * Different colors for: 
    * Sabbatical
    * Parental leave / research leave
    * No longer active
* @natalynyu implement in table
* @chrxr to ask Kathy whether this is a well used feature, and whether we need to include "Sabbatical eligible".

**Comment by Vittorio2015** [comment]
(Work in progress...)
## Color recommendations to highlight the absentee status
### Alternative A - background color
- Sabbatical - "negative: medium" `background: rgb(255, 64, 64);`
- Parental leave - "negative: light" `background: rgb(255, 143, 156);`
- No longer active - "Background: medium" `background: rgb(209, 209, 209);`
### Alternative A accessibility consequences 
- The color for the borderless icon (`#4e88c7`) must be `#000000` instead, for sufficient contrast with any of these Mark One palette colors
- The hover color of table rows matches the color of "No longer active" (The lighter option of grey "Background: subtle" matches the color of the grey table rows
![image](https://user-images.githubusercontent.com/12190138/106511489-4af34780-649e-11eb-92c6-9fe2479a6e68.png)

**Comment by natalynyu** [comment]
This looks great Vittorio! Thank you so much for putting this together.
I just wanted to add some discussion points/ideas from our meeting:

**Option A**

- @chrxr - Because of the color contrast issue between the edit icon and the `negative.medium` background color for the Sabbatical cell, can we use the same background color as the one being used for Parental Leave, `negative.light`? Are the users requesting that the two background colors differ, or was this a design choice of the original application?
![image](https://user-images.githubusercontent.com/29589689/106776484-1902f200-6612-11eb-93b8-87b5be16d471.png)
- If the users want the background color of Sabbatical vs. Parental Leave cells to differ, perhaps we can choose a new color for `negative.medium` that works (contrast-wise) for both the text and the icon color. 

**Option B**

- The advantage to this option is that we do not have to worry about color contrast. 
- This is a nice alternative to Option A if it isn't possible to update `negative.medium` to a color that works contrast-wise with both the text and icon color. 

**Option C**
- I prefer Option B to Option C, as I think that Option B makes it much more clear which cells are being highlighted. Especially for a table of this size, in the case that there are absences on sequential rows, Option C could make it hard to distinguish which cells are being highlighted (top cell or bottom?).

**Comment by Vittorio2015** [comment]
Thanks for your feedback @natalynyu . I just checked and none of the light colors on the Marck One palette offer enough accessible contrast with the `#4E88C7` color of the edit icon.

**Comment by natalynyu** [comment]
@Vittorio2015 Thanks for looking into this! Would it be possible to change the Mark One negative light color so that the color contrast is acceptable in conjunction with the edit icon color? Option A would be the easiest to implement, but the color contrast is definitely an issue.

**Comment by Vittorio2015** [comment]
Per @natalynyu and @jonseitz recommendation
## Color recommendations to highlight the absentee status
### Alternative D - font color and weight
- Mark One `negative: dark` and `font-weight: bold;` for absentee status
- Mark One `negative: dark` and `font-weight: bold;` for absentee status ad adjacent courses

![image](https://user-images.githubusercontent.com/12190138/107266855-1b9b8800-6a14-11eb-94bb-ea8f3bafa541.png)

**Comment by Vittorio2015** [comment]
## Color recommendations to highlight the absentee status
### Alternative D - font color and weight

After @natalynyu 's prompting, I tested color contrast, and the `negative: medium` doesn’t have enough contrast with the dark table rows (`#ececec`), nor does negative-dark  (`hsl(356deg 85% 52%)`). 
We should use the color of `Background: accent` (`rgb(165, 28, 48);`) for sufficient color contrast.

**Comment by jonseitz** [comment]
@Vittorio2015 We do have a separate negative **text** color defined in the mark-one theme `#ff4040`. Does that provide enough contrast against the dark table rows?

**Comment by natalynyu** [comment]
@jonseitz The negative `text` color is the same as the `negative:medium` `background` color, `#ff4040.` As a workaround, I added the accent color that Vittorio recommended to the list of `text` colors - is this ok? I figure that it doesn't semantically make sense to use a background color for a text color.
![image](https://user-images.githubusercontent.com/29589689/107541038-b622d500-6b94-11eb-9c62-238b18fe9610.png)

**Comment by jonseitz** [comment]
@natalynyu oh, right. My bad.

I agree that it doesn't make sense semantically to use a `background` color for text, but by that same token we should try to give the name of the text color we do use some meaning, since `accent` is a little ambiguous (and not that it's a major issue, but `#a51c30` is the official harvard crimson).

My preference would be update the negative text color to something that does does have an accessible level of contrast. Otherwise we'll have a color in our styleguide that we can't actually use. @Vittorio2015 any thoughts on what a better color for negative text would be?

**Comment by Vittorio2015** [comment]
@jonseitz, if I understand [your comment](https://github.com/seas-computing/course-planner/issues/300#issuecomment-776846749) correctly, please notice that `negative:medium` background color (`#ff4040`) is not an accessible color when used over grey table rows (`#ececec`).
If you need to create an accent color with an appropriate name for font color, use the same color used for `Background: accent` (`rgb(165, 28, 48);` or `a51c30`) since any other red color in the [Mark One palette](https://seas-computing.github.io/mark-one/#/Theme?id=globalcss) doesn't have enough accessible contrast when used over grey table rows (`#ececec`).

**Comment by Vittorio2015** [comment]
@jonseitz , @natalynyu just helped me to understand your suggestion. Sure, let's change  `negative: dark` from the current `rgb(237, 27, 42)` to the same color of `Background: accent` (`rgb(165, 28, 48)`).

**Comment by natalynyu** [comment]
@Vittorio2015 @jonseitz Thanks for looking into this! My original thought was to use the accent color as the negative text color, but after realizing that the accent color is Harvard's official color, I'm wondering if we should use a different color since the red text color will be indicating missing information in the Faculty table. Is this a problem?

**Comment by Vittorio2015** [comment]
@natalynyu and @jonseitz , I don't think that we should be concerned about using the "Harvard color" for this application. Red clearly indicates (in Western culture) "negative" or "alert" and especially in this case, it highlights the possible occurrence of something wrong (as faculty erroneously assigned to teach a course during absence).
If we are concerned about repercussions or just the use of this color for Harvard branding in other products using Mark One, we could use for `negative: dark` the color `#C9223B`, which is a bit lighter than the "Harvard color" although with accessible contrast, also against grey table rows.

**Comment by jonseitz** [comment]
Thanks, @Vittorio2015. My vote would be to use `#c9223b` as the `text:negative` color, and then use that for the text in those cells.

**Comment by natalynyu** [comment]
@Vittorio2015 @jonseitz Ok, great! I'll update the `text: negative` color to `#c9223b`. Thanks all!

**Comment by natalynyu** [comment]
Here's an example of using `#c9223b` as the text color with a bold font weight:
<img width="1279" alt="Screen Shot 2021-02-12 at 1 21 07 PM" src="https://user-images.githubusercontent.com/29589689/107806758-3f710d80-6d35-11eb-8c77-9e9e5b1e1dc1.png">

**Comment by natalynyu** [comment]
@Vittorio2015 Is the color contrast between the medium text (`#717171`) and the table cell backgrounds sufficient?
![image](https://user-images.githubusercontent.com/29589689/108085268-2624d580-7043-11eb-9174-7a6d2bff1dec.png)

**Comment by Vittorio2015** [comment]
@natalynyu , font `color:` `#717171`  doesn't have sufficient contrast over both light (`#ececec`) and dark (on `hover`) colors of table rows (`#d1d1d1`)
Darkening font `color:` `#717171` to `#575757` would allow for sufficient contrast on both colors.

For the same reason, font `color:` `#c9223b` should be darkened to `#A61C31` (which is close to Harvard `#A51C30` but not quite the same). Apologies for not catching this earlier but, unfortunately, I didn't check for the color contrast with `hover` darker table color rows.

**Comment by natalynyu** [comment]
@Vittorio2015 Got it, thanks for checking this for me! I've made the changes to both text colors. The most updated text colors are now `#575757` and `#A61C31`.

**Comment by jonseitz** [comment]
@Vittorio2015 I think `#a61c31` is still going to be too close to our `accent` color. What about something like `#bd0f24`? It's still fairly close, but I think it should be differentiated a little bit more.

(I found that by taking the original SEAS red that we were using, `#ed1b34`, plugging it into [an online color chooser](https://www.w3schools.com/colors/colors_picker.asp) and choosing a value that was a few percentage points darker.)

**Comment by Vittorio2015** [comment]
@jonseitz , I agree to use `#bd0f24`. 

## Table row colors

With regard to your suggestion to lighten up the table row colors and avoid further color changes on fonts and icons, I would recommend changing hover color of table rows from `#d1d1d1` to a lighter `#E8E8E8`, and changing the darker table rows from `#ececec` to a lighter `#f2f2f2` to allow for a more evident contrast on mouse-hover.
The above recommendations allow accessible color contrast also to current icons in `#4E88C7`

**Comment by natalynyu** [comment]
@jonseitz @Vittorio2015 Sounds good. This is how the `#bd0f24` looks in the table:
![image](https://user-images.githubusercontent.com/29589689/108386539-bc3f3400-71da-11eb-8005-153116f013b9.png)

**Comment by jonseitz** [comment]
Resolved by #309
