### ISSUE TITLE
Course instance table: Controller methods for course instance table Views

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#428]

**Comment by jonseitz** [comment]
@rmainseas Sure, I think that breakdown makes sense. Are you still thinking that each bullet point would be a separate PR, or would each ticket be a separate PR? 

One more thing that I just realized we've overlooked is some kind of `ViewResponseDTO` that represents the data we'll be receiving on the frontend. I _think_ the `typeorm` decorators will cause problems if we just use the `View` class, and the `createdAt` and `updatedAt` fields may cause some type issues since we don't select those by default.

**Comment by rmainseas** [comment]
@jonseitz I was thinking that each bullet would be a separate PR to keep them really small. So one ticket would be delivered by many PRs.

You're absolutely right about the `ViewResponseDTO` - we shouldn't be using the `View` class as it's an entity class not a DTO class. Even if it _did_ work, it would be mixing concerns between the database schema and API response. Those two are _often_ the same but not always (q.v. course instances and non-class meetings). Another consideration being that if we _did_ use entity classes like that -  we would also have to pull them in on the front end which would then probably pull a bunch of NestJS and TypeORM junk into the client-side bundle.
