### ISSUE TITLE
Course instance table: Enrollment table fields

### ISSUE THREAD

**Issue by chrxr** [seas-computing/course-planner#479]
This ticket implements the ability for a user to see the enrollment data for a course instance. 

As described in the notes below, this will merge the existing three enrollment columns into one single column.

This ticket does not include the enrollment modal, or the ability to edit / save changes to the enrollment for a course instance.

**Comment by Vittorio2015** [comment]
## Draft 1

### Icons

- Eliminate the three columns under Enrollment
- Use the column header as a legend for the icons that represent
   - (Pre) students registering in shopping week
   - (Study card) students who add the course in my.harvard by the submission deadline
   - (Actual) students who actually took the course

_Screen capture of [prototype](https://seas-computing.github.io/course-planner_ux/courses.html)_
![image](https://user-images.githubusercontent.com/12190138/158463832-a70ebd19-8494-47ee-b505-60fdbc153ba1.png)

**Comment by Vittorio2015** [comment]
## Draft 2

### Icons with tooltip, no icons in table header

- Eliminate the three columns under Enrollment
- Fall 2019 header example - Use the column header as a legend for the icons that represent
- Spring 2020 no-header example - No icons in column header
- Tooltips for each icon upon mouse-over
    - Pre enrolled students
    - Sudents with study card
    - Actual enrolled students

_Screen capture of [prototype](https://seas-computing.github.io/course-planner_ux/courses.html)_
![image](https://user-images.githubusercontent.com/12190138/158617462-61b8bfaa-209d-47ab-8d99-91dc7ae27316.png)

**Comment by Vittorio2015** [comment]
## Draft 2

### Icons with tooltip, no icons in table header

- Eliminate the three columns under Enrollment
- Fall 2019 header example - Use the column header as a legend for the icons that represent
- Spring 2020 no-header example - No icons in column header
- Tooltips for each icon upon mouse-over
    - Pre enrolled students
    - Sudents with study card
    - Actual enrolled students

_Screen capture of [prototype](https://seas-computing.github.io/course-planner_ux/courses.html)_
![image](https://user-images.githubusercontent.com/12190138/158617462-61b8bfaa-209d-47ab-8d99-91dc7ae27316.png)

**Comment by chrxr** [comment]
Alert message to be between the "cancel" and "save" buttons, matching our existing modal format.

**Comment by Vittorio2015** [comment]
## UI Recommendations
[@rmain](https://seasarc.slack.com/team/U03707ASD7E) , Screen reader read `aria-label` of  Pre-Registration, Enrollment Deadline, and Final Enrollment. Adding the specific course info next to each would be great but not essential.
Esthetically (see first screen capture below), I don’t think we need `border-bottom` and vertical `padding` can just be 2px, rather than 10px. I also used `<small>` on the icons only, since they are not buttons (like notes)
I am tempted to ask whether this list can change to `display: flex;` and display the icons and numbers on one line (see second screen capture below) in situations with plenty of horizontal room.

![image](https://user-images.githubusercontent.com/12190138/168381032-2f63fef8-3f40-49bf-8d96-bcac54414648.png)
![image](https://user-images.githubusercontent.com/12190138/168381069-c3193af0-2e8f-475f-a1a6-1cd3a5038150.png)
